import styles from '../student/StudentHomePage.module.css';

export const ICONS: Record<string, React.ReactNode> = {
  shield: <span className={styles.icon}>🛡️</span>,
  users: <span className={styles.icon}>👥</span>,
  'users-cog': <span className={styles.icon}>🧑‍🔧</span>,
  university: <span className={styles.icon}>🏫</span>,
  book: <span className={styles.icon}>📚</span>,
  database: <span className={styles.icon}>💾</span>,
  'bar-chart': <span className={styles.icon}>📊</span>,
  activity: <span className={styles.icon}>⚡</span>,
  key: <span className={styles.icon}>🔑</span>,
  'refresh-cw': <span className={styles.icon}>🔄</span>,
  'book-open': <span className={styles.icon}>📖</span>,
  settings: <span className={styles.icon}>⚙️</span>,
  clock: <span className={styles.icon}>⏰</span>,
  'log-in': <span className={styles.icon}>🔓</span>,
  home: <span className={styles.icon}>🏠</span>,
  'edit-3': <span className={styles.icon}>📝</span>,
  user: <span className={styles.icon}>👤</span>,
  'check-square': <span className={styles.icon}>✅</span>,
  layers: <span className={styles.icon}>🗂️</span>,
  list: <span className={styles.icon}>📋</span>,
  edit: <span className={styles.icon}>✏️</span>,
  'bar-chart-2': <span className={styles.icon}>📈</span>,
  grid: <span className={styles.icon}>🔲</span>,
  bell: <span className={styles.icon}>🔔</span>,
  'file-text': <span className={styles.icon}>📄</span>,
  'help-circle': <span className={styles.icon}>❓</span>,
  upload: <span className={styles.icon}>⬆️</span>,
  download: <span className={styles.icon}>⬇️</span>,
};
